export const PRODUCTION_DOMAIN = 'victorsamuel.com';
export const GOOGLE_TAG_MANAGER_CONTAINER_ID = 'GTM-N4GFJ9H';
export const PRODUCTION_GOOGLE_ANALYTICS_ID = 'G-08DKWB07ES';
export const TESTING_GOOGLE_ANALYTICS_ID = 'G-6KZMNJMSQ3';
